const navToggle=document.querySelector('[data-nav-toggle]');
const navMenu=document.querySelector('[data-nav-menu]');
navToggle?.addEventListener('click',()=>{const open=navMenu.classList.toggle('open');navToggle.setAttribute('aria-expanded',String(open));});
navMenu?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{navMenu.classList.remove('open');navToggle?.setAttribute('aria-expanded','false');}));
const drawer=document.querySelector('[data-drawer]');
const backdrop=document.querySelector('[data-drawer-backdrop]');
const openDrawer=()=>{drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.hidden=false;document.body.style.overflow='hidden';drawer.querySelector('input')?.focus();};
const closeDrawer=()=>{drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');backdrop.hidden=true;document.body.style.overflow='';};
document.querySelectorAll('[data-open-drawer]').forEach(btn=>btn.addEventListener('click',openDrawer));
document.querySelector('[data-close-drawer]')?.addEventListener('click',closeDrawer);
backdrop?.addEventListener('click',closeDrawer);
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDrawer();});
document.querySelectorAll('form').forEach(form=>form.addEventListener('submit',event=>{event.preventDefault();alert('Thank you. Our team will contact you shortly.');form.reset();closeDrawer();}));
